version: '3'

networks:
  rabbitmq_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.7.4
    container_name: RabbitMQ
    networks:
      - rabbitmq_network
    ports:
      - "5672:5672"

  api-gateway:
    build: ./api-gateway
    image: claclacla/api-gateway
    container_name: ApiGateway
    environment:
      - APP_ENV=development
    networks:
      - rabbitmq_network
    ports:
      - 3000:3000
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    links:
      - rabbitmq
    tty: true
    stdin_open: true

  order-insert:
    build: ./ruby-microservice
    image: claclacla/ruby-microservice
    container_name: OrderInsert
    environment:
      - MICROSERVICE_PATH=/usr/src/app/order/insert/app.rb  
      - APP_ENV=development
    networks:
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    links:
      - rabbitmq
    tty: true
    stdin_open: true

  order-notifications-dispatcher:
    build: ./ruby-microservice
    image: claclacla/ruby-microservice
    container_name: OrderNotificationsDispatcher
    environment:
      - MICROSERVICE_PATH=/usr/src/app/order/notifications-dispatcher/app.rb  
      - APP_ENV=development
    networks:
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    links:
      - rabbitmq
    tty: true
    stdin_open: true

  dispatcher-manager:
    build: ./ruby-microservice-api
    image: claclacla/ruby-microservice-api
    container_name: DispatcherManager
    environment:
      - MICROSERVICE_PATH=/usr/src/app/dispatcher/manager/app.rb
      - APP_ENV=development
    networks:
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    links:
      - rabbitmq
    tty: true
    stdin_open: true

  web-server:
    build: ./web-server
    image: claclacla/spa-http-server
    container_name: WebServer
    ports:
      - 8080:8080
    volumes:
      - "${APP_FOLDER}/docker/dev/web-server/public:/usr/src/app"

  order-socket:
    build: ./js-microservice
    image: claclacla/js-microservice
    container_name: OrderSocket
    environment:
      - MICROSERVICE_PATH=/usr/src/app/order/socket/app.js
      - APP_ENV=development
    networks:
      - rabbitmq_network
    ports:
      - 3001:3001
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    links:
      - rabbitmq
    tty: true
    stdin_open: true