version: '3'

networks:
  rabbitmq_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.7.4
    container_name: RabbitMQ
    networks:
      - rabbitmq_network
    ports:
      - "5672:5672"

  api-gateway:
    build: ./api-gateway
    image: claclacla/api-gateway
    container_name: ApiGateway
    environment:
      - APP_ENV=development
    networks:
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    ports:
      - "3000:4567"

  order-insert-logic:
    build: ./order/insert-logic
    image: claclacla/order-insert-logic
    container_name: OrderInsertLogic
    environment:
      - APP_ENV=development
    networks:
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    tty: true
    stdin_open: true

  order-notifications-dispatcher:
    build: ./order/notifications-dispatcher
    image: claclacla/order-notifications-dispatcher
    container_name: OrderNotificationsDispatcher
    environment:
      - APP_ENV=development
    networks:
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    tty: true
    stdin_open: true

  dispatcher-manager:
    build: ./dispatcher/manager
    image: claclacla/dispatcher-manager
    container_name: DispatcherManager
    environment:
      - APP_ENV=development
    networks:
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    tty: true
    stdin_open: true