version: '3'

networks:
  rabbitmq_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.7.4
    container_name: RabbitMQ
    networks:
      - rabbitmq_network
    ports:
      - "5672:5672"

  dispatcher-manager:
    build: ./dispatcher/manager
    image: claclacla/dispatcher-manager
    container_name: DispatcherManager
    networks:
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"

  order-notifications-dispatcher:
    build: ./order/notifications-dispatcher
    image: claclacla/order-notifications-dispatcher
    container_name: OrderNotificationsDispatcher
    networks:
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"

  order-insert-logic:
    build: ./order/insert-logic
    image: claclacla/order-insert-logic
    container_name: OrderInsertLogic
    networks:
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"    